name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics.plugin.wakatime.svg
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, languages-graphs,
          plugin_wakatime_days: 7,
          plugin_wakatime_repositories_visibility: all,
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}